kind: Service
metadata:
  name: darwin-prometheus-service
  namespace: darwin
spec:
  type: NodePort
  selector:
    app: darwin-prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 30000
  externalIPs:
    - 10.0.0.100