kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: darwin
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 1m

    rule_files:
      - /etc/prometheus/rules/*.rules

    scrape_configs:
      - job_name: 'darwin-service-1'
        scrape_interval: 5s
        static_configs:
          - targets: ['darwin-service-1:80']
        relabel_configs:
          - source_labels: [job]
            target_label: job
            replacement: 'darwin-new-service'
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 4Gi
            cpu: 2

        alerting:
          alertmanagers:
            - static_configs:
                - targets:
                    - alertmanager:9093
      - job_name: 'darwin-service-2'
        scrape_interval: 10s
        static_configs:
          - targets: ['darwin-service-2:80']
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 1

        alerting:
          alertmanagers:
            - static_configs:
                - targets:
                    - alertmanager:9093