{
 "title": "Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage Per Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-109.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-109.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-109.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-137.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-137.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-137.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-147.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-147.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-147.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-151.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-151.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-151.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-155.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-155.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-155.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-220.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-220.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-220.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-242.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-242.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-242.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-10.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-10.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-10.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-25.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-25.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-25.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-29.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-29.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-29.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-40.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-40.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-40.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-53.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-53.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-53.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-34-73.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-34-73.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-34-73.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-35-41.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-35-41.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-35-41.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-35-45.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-35-45.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-35-45.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-35-47.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-35-47.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-35-47.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-35-57.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-35-57.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-35-57.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-35-64.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-35-64.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-35-64.eu-west-1.compute.internal\"} * 100"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"ip-10-197-35-85.eu-west-1.compute.internal\"} - node_memory_MemAvailable_bytes{instance=\"ip-10-197-35-85.eu-west-1.compute.internal\"}) / node_memory_MemTotal_bytes{instance=\"ip-10-197-35-85.eu-west-1.compute.internal\"} * 100"
    }
   ]
  },
  {
   "title": "Cpu Usage per Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-10.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Infra1 (ip-10-197-34-10)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-25.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker1 (ip-10-197-34-25)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-29.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker2 (ip-10-197-34-29)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-40.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker3 (ip-10-197-34-40)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-53.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Master1 (ip-10-197-34-53)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-73.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker4 (ip-10-197-34-73)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-109.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker5 (ip-10-197-34-109)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-137.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker6 (ip-10-197-34-137)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-151.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker7 (ip-10-197-34-151)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-155.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Infra2 (ip-10-197-34-155)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-220.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Master2 (ip-10-197-34-220)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-34-242.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker8 (ip-10-197-34-242)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-35-41.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker9 (ip-10-197-35-41)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-35-45.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker10 (ip-10-197-35-45)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-35-47.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Infra3 (ip-10-197-35-47)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-35-57.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Master3 (ip-10-197-35-57)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-35-64.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker11 (ip-10-197-35-64)"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance = \"ip-10-197-35-85.eu-west-1.compute.internal\"}[2m])) * 100)",
     "legendFormat": "Worker12 (ip-10-197-35-85)"
    }
   ]
  },
  {
   "title": "Nodes NotReady",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status!=\"true\"}"
    }
   ]
  }
 ]
}