{
 "title": "Overview Cluster Health Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "label_values(node)" } },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "application",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", node=~\"$node\", status!=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodo Unschedulable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodos",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node!=\"\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", node!=\" \", status!=\"true\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "CPU TOTAL",
   "type": "stat",
   "description": "Cores totales que hay en el cluster.",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{kubernetes_io_hostname=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memoria TOTAL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(machine_memory_bytes{kubernetes_io_hostname=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", node=~\"$node\", status!=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodo no Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU en uso",
   "type": "stat",
   "description": "Consumo de la CPU ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(avg by(mode)(rate(node_cpu_seconds_total{job=\"kubernetes-service-endpoints\", mode=~\"idle|iowait|steal\"}[5m])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memoria en uso",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum (node_memory_MemAvailable_bytes)/ sum (node_memory_MemTotal_bytes{job=\"kubernetes-service-endpoints\"}))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consumo de Nodos CPU/Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU usada por Nodo",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": " (100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=~\"idle\", instance!=\" \"}[2m]))*100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance!=\" \"} - node_memory_MemAvailable_bytes{instance!=\" \"}) / node_memory_MemTotal_bytes{instance!=\" \"}*100",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}